flowchart LR
    V[Visiteur]
    A[Acheteur]
    S[Vendeur]
    AD[Administrateur]
    SP[Agent support]

    U1((Creer un compte))
    U2((Se connecter))
    U3((Consulter les annonces))
    U4((Publier une annonce))
    U5((Modifier/Supprimer une annonce))
    U6((Ajouter au panier))
    U7((Passer commande))
    U8((Effectuer paiement))
    U9((Suivre commande))
    U10((Envoyer message))
    U11((Recevoir notifications))
    U12((Moderer contenus))
    U13((Gerer utilisateurs))
    U14((Traiter litiges))

    V --> U1
    V --> U3
    A --> U2
    A --> U3
    A --> U6
    A --> U7
    A --> U8
    A --> U9
    A --> U10
    A --> U11
    S --> U2
    S --> U4
    S --> U5
    S --> U9
    S --> U10
    S --> U11
    AD --> U12
    AD --> U13
    SP --> U14
