<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Liste des pays supportés
    |--------------------------------------------------------------------------
    |
    | Liste complète des pays disponibles dans l'application avec leurs codes ISO
    | et informations pour la gestion géographique multi-pays.
    |
    */

    'countries' => [
        [
            'name' => 'République Démocratique du Congo',
            'name_en' => 'Democratic Republic of the Congo',
            'code' => 'COD',
            'code_alpha2' => 'CD',
            'flag' => '🇨🇩',
            'phone_code' => '+243',
            'currency' => 'CDF',
            'timezone' => 'Africa/Kinshasa',
            'latitude' => -4.0383,
            'longitude' => 21.7587,
            'is_default' => true,
        ],
        [
            'name' => 'Congo (Brazzaville)',
            'name_en' => 'Republic of the Congo',
            'code' => 'COG',
            'code_alpha2' => 'CG',
            'flag' => '🇨🇬',
            'phone_code' => '+242',
            'currency' => 'XAF',
            'timezone' => 'Africa/Brazzaville',
            'latitude' => -0.228021,
            'longitude' => 15.827659,
            'is_default' => false,
        ],
        [
            'name' => 'Rwanda',
            'name_en' => 'Rwanda',
            'code' => 'RWA',
            'code_alpha2' => 'RW',
            'flag' => '🇷🇼',
            'phone_code' => '+250',
            'currency' => 'RWF',
            'timezone' => 'Africa/Kigali',
            'latitude' => -1.940278,
            'longitude' => 29.873888,
            'is_default' => false,
        ],
        [
            'name' => 'Burundi',
            'name_en' => 'Burundi',
            'code' => 'BDI',
            'code_alpha2' => 'BI',
            'flag' => '🇧🇮',
            'phone_code' => '+257',
            'currency' => 'BIF',
            'timezone' => 'Africa/Bujumbura',
            'latitude' => -3.373056,
            'longitude' => 29.918886,
            'is_default' => false,
        ],
        [
            'name' => 'Ouganda',
            'name_en' => 'Uganda',
            'code' => 'UGA',
            'code_alpha2' => 'UG',
            'flag' => '🇺🇬',
            'phone_code' => '+256',
            'currency' => 'UGX',
            'timezone' => 'Africa/Kampala',
            'latitude' => 1.373333,
            'longitude' => 32.290275,
            'is_default' => false,
        ],
        [
            'name' => 'Tanzanie',
            'name_en' => 'Tanzania',
            'code' => 'TZA',
            'code_alpha2' => 'TZ',
            'flag' => '🇹🇿',
            'phone_code' => '+255',
            'currency' => 'TZS',
            'timezone' => 'Africa/Dar_es_Salaam',
            'latitude' => -6.369028,
            'longitude' => 34.888822,
            'is_default' => false,
        ],
        [
            'name' => 'Kenya',
            'name_en' => 'Kenya',
            'code' => 'KEN',
            'code_alpha2' => 'KE',
            'flag' => '🇰🇪',
            'phone_code' => '+254',
            'currency' => 'KES',
            'timezone' => 'Africa/Nairobi',
            'latitude' => -0.023559,
            'longitude' => 37.906193,
            'is_default' => false,
        ],
        [
            'name' => 'Zambie',
            'name_en' => 'Zambia',
            'code' => 'ZMB',
            'code_alpha2' => 'ZM',
            'flag' => '🇿🇲',
            'phone_code' => '+260',
            'currency' => 'ZMW',
            'timezone' => 'Africa/Lusaka',
            'latitude' => -13.133897,
            'longitude' => 27.849332,
            'is_default' => false,
        ],
        [
            'name' => 'Angola',
            'name_en' => 'Angola',
            'code' => 'AGO',
            'code_alpha2' => 'AO',
            'flag' => '🇦🇴',
            'phone_code' => '+244',
            'currency' => 'AOA',
            'timezone' => 'Africa/Luanda',
            'latitude' => -11.202692,
            'longitude' => 17.873887,
            'is_default' => false,
        ],
        [
            'name' => 'Afrique du Sud',
            'name_en' => 'South Africa',
            'code' => 'ZAF',
            'code_alpha2' => 'ZA',
            'flag' => '🇿🇦',
            'phone_code' => '+27',
            'currency' => 'ZAR',
            'timezone' => 'Africa/Johannesburg',
            'latitude' => -30.559482,
            'longitude' => 22.937506,
            'is_default' => false,
        ],
        [
            'name' => 'Cameroun',
            'name_en' => 'Cameroon',
            'code' => 'CMR',
            'code_alpha2' => 'CM',
            'flag' => '🇨🇲',
            'phone_code' => '+237',
            'currency' => 'XAF',
            'timezone' => 'Africa/Douala',
            'latitude' => 7.369722,
            'longitude' => 12.354722,
            'is_default' => false,
        ],
        [
            'name' => 'Gabon',
            'name_en' => 'Gabon',
            'code' => 'GAB',
            'code_alpha2' => 'GA',
            'flag' => '🇬🇦',
            'phone_code' => '+241',
            'currency' => 'XAF',
            'timezone' => 'Africa/Libreville',
            'latitude' => -0.803689,
            'longitude' => 11.609444,
            'is_default' => false,
        ],
        [
            'name' => 'Centrafrique',
            'name_en' => 'Central African Republic',
            'code' => 'CAF',
            'code_alpha2' => 'CF',
            'flag' => '🇨🇫',
            'phone_code' => '+236',
            'currency' => 'XAF',
            'timezone' => 'Africa/Bangui',
            'latitude' => 6.611111,
            'longitude' => 20.939444,
            'is_default' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Villes principales par pays
    |--------------------------------------------------------------------------
    */

    'major_cities' => [
        'COD' => [
            ['name' => 'Kinshasa', 'latitude' => -4.3276, 'longitude' => 15.3136, 'population' => 17000000],
            ['name' => 'Lubumbashi', 'latitude' => -11.6795, 'longitude' => 27.4794, 'population' => 2800000],
            ['name' => 'Mbuji-Mayi', 'latitude' => -6.1200, 'longitude' => 23.5900, 'population' => 3500000],
            ['name' => 'Kananga', 'latitude' => -5.8967, 'longitude' => 22.4169, 'population' => 1500000],
            ['name' => 'Kisangani', 'latitude' => 0.5150, 'longitude' => 25.1908, 'population' => 1800000],
            ['name' => 'Goma', 'latitude' => -1.6792, 'longitude' => 29.2228, 'population' => 1000000],
            ['name' => 'Bukavu', 'latitude' => -2.5110, 'longitude' => 28.8593, 'population' => 900000],
            ['name' => 'Kolwezi', 'latitude' => -10.7150, 'longitude' => 25.4667, 'population' => 500000],
        ],
        'COG' => [
            ['name' => 'Brazzaville', 'latitude' => -4.2634, 'longitude' => 15.2429, 'population' => 2400000],
            ['name' => 'Pointe-Noire', 'latitude' => -4.7960, 'longitude' => 11.8640, 'population' => 1200000],
        ],
        'RWA' => [
            ['name' => 'Kigali', 'latitude' => -1.9403, 'longitude' => 29.8739, 'population' => 1200000],
            ['name' => 'Butare', 'latitude' => -2.5978, 'longitude' => 29.7386, 'population' => 150000],
        ],
        'BDI' => [
            ['name' => 'Bujumbura', 'latitude' => -3.3614, 'longitude' => 29.3599, 'population' => 1100000],
            ['name' => 'Gitega', 'latitude' => -3.4271, 'longitude' => 29.9246, 'population' => 150000],
        ],
        'KEN' => [
            ['name' => 'Nairobi', 'latitude' => -1.2864, 'longitude' => 36.8172, 'population' => 5000000],
            ['name' => 'Mombasa', 'latitude' => -4.0435, 'longitude' => 39.6682, 'population' => 1500000],
        ],
    ],
];
